### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by madmaxio** [steffengy/winauth-rs#3]
Hello, is thing still supported or perhaps you know some other rust based solution?

**Comment by steffengy** [comment]
It works, sure. 
I'm not aware of any other solution in rust.

If you want to let me know what you're trying to do, 
I might be able to point you in the right direction.

**Comment by madmaxio** [comment]
The task is to to do rust based windows domain authorization for web app, so iI need something similar to jespa http://www.ioplex.com/.

**Comment by steffengy** [comment]
I'm only aware of
https://github.com/StratumSecurity/ntlm-connector
and 
https://github.com/steffengy/winauth-rs/tree/master/hyper
in rust which are both using winauth
and afaik both only implement the client side.

**Comment by madmaxio** [comment]
Can you please provide some absolutely newbie friendly example how to use this thing? I mean, the most dumbed down one.

**Comment by steffengy** [comment]
First the [documentation](https://docs.rs/winauth/0.0.3/x86_64-pc-windows-msvc/winauth/) is really straightforward, there aren't more than a handful methods.
The hard part is really not the API but integrating it for HTTP auth as you want,
where example implementations luckily already exist which - as mentioned -
only require a little bit of willingness to go through them.

The general steps (no matter if HTTP or whatever protocol) are always the same:
- intantiate a builder (winauth::NtlmV2ClientBuilder::new) or for SSO windows-only authentication (NtlmSspiBuilder).
- configure it (pretty much only in the non-sso case)
- call build
- call next_bytes on the result, send to client, receive, call next_bytes with the response again and repeat until it doesn't want any more input (==>handshake done)

A few general examples can be found in the tests themselves:
general: https://github.com/steffengy/winauth-rs/blob/master/winauth/src/lib.rs#L876
windows-specific: https://github.com/steffengy/winauth-rs/blob/master/winauth/src/windows.rs#L201

**Comment by madmaxio** [comment]
Thank you for amazing answer, will try. 
If I will fail with my attempts is it possbile to contact you later about payment for solution I'm looking for?

**Comment by steffengy** [comment]
Should your solution end up generic enough, I'd appreciate a PR for the old [hyper integration](https://github.com/steffengy/winauth-rs/tree/master/hyper) (I guess you will be using hyper?) in this repo. 
If you have questions along the way, let me know.

For business inquiries, you can contact me via email.
