### ISSUE TITLE
Would love an example of how to use it!

### ISSUE THREAD

**Issue by gilescope** [steffengy/winauth-rs#4]

**Comment by gilescope** [comment]
There's a test at the end of hyper/src/lib.rs that shows it working. Would be great to have an explicit /examples dir as well.

**Comment by steffengy** [comment]
For the hyper integration part?
I guess first would be to check if that part still works with hyper 0.12 as is.

I don't plan to do that, since I do not use the hyper-part personally and the last person that wanted it instead went with some forked self-built version, if I remember correctly.

**Comment by steffengy** [comment]
Since we now have a more generic http interface and examples, closing this for now.
